name: Publish Images

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.IPC_DEPLOY_KEY }}
          ${{ secrets.BUILTIN_ACTORS_DEPLOY_KEY }}
          ${{ secrets.RUST_RECALL_DEPLOY_KEY }}
          ${{ secrets.CONTRACTS_DEPLOY_KEY }}

    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Docker Prep
      id: prep
      run: |
        # Get the short commit hash (first 7 characters of GITHUB_SHA).
        COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
        # Format the version string as sha-[short-commit-hash].
        VERSION="sha-$COMMIT_HASH"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Prepare git and ssh config for build context
      run: |
        mkdir root-config
        cp -r ~/.gitconfig ~/.ssh root-config

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        ssh: default=${{ env.SSH_AUTH_SOCK }}
        file: ./ci.Dockerfile
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: textilemachine/recall-s3:latest,textilemachine/recall-s3:${{ steps.prep.outputs.VERSION }}
        platforms: linux/amd64,linux/arm64
