name: Publish Images

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Docker Prep
      id: prep
      run: |
        # Get the short commit hash (first 7 characters of GITHUB_SHA).
        COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
        # Format the version string as sha-[short-commit-hash].
        VERSION="sha-$COMMIT_HASH"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ./Dockerfile
        push: true
        tags: textilemachine/basin-s3:latest,textilemachine/basin-s3:${{ steps.prep.outputs.VERSION }}
        platforms: linux/amd64, linux/arm64